name: Checks

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies (root)
        run: npm install

      - name: Run checks (root script)
        run: npm run checks
